#© 2023 Enest Dembedza

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-enest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-enest
  template:
    metadata:
      labels:
        app: prod-stedi-enest
    spec:
      containers:
        - name: prod-stedi-enest
          image: gcr.io/cubs-consulting/stedi # Ensure this image refers to the correct Artifact registry repository
		  env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-enest
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-enest"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: enest-twilio-dev
                  key: twilio_token
				  ports:
            - containerPort: 443 # The application inside the container should listen on this port for HTTPS traffic
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 443 # Updated to the HTTPS port
              scheme: HTTPS # Added scheme for HTTPS
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-enest-nodeport
spec:
  selector:
    app: prod-stedi-enest
  type: NodePort
  ports:
    - port: 443 # Changed from 80 to 443 for HTTPS
      targetPort: 443 # Should match the containerPort for HTTPS traffic
      protocol: TCP # Explicitly define the protocol as TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-enest-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-enest-public # Ensure this IP has been created and is associated with the ingress
    networking.gke.io/managed-certificates: prod-stedi-enest-certificate
    kubernetes.io/ingress.allow-http: "false" # Uncommented to force HTTPS by redirecting 
	HTTP to HTTPS
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-enest-nodeport
            port:
              number: 443 # Updated to the HTTPS port
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-enest-certificate
spec:
  domains:
    - enest.cit262.com # Ensure this domain is registered and pointing to the static IP